DROP DATABASE IF EXISTS TESTING_SYSTEM_ASSIGNMENT_2;
CREATE DATABASE TESTING_SYSTEM_ASSIGNMENT_2;
USE TESTING_SYSTEM_ASSIGNMENT_2;

CREATE TABLE DEPARTMENT (
DEPARTMENTID	TINYINT UNSIGNED PRIMARY KEY,
DEPARTMENTNAME	VARCHAR(50)
);

CREATE TABLE POSITION (
POSITIONID		TINYINT UNSIGNED PRIMARY KEY ,
POSITIONNAME	ENUM ('Dev', 'Test', 'Scrum Master' ,'PM')
);

CREATE TABLE `ACCOUNT` (
ACCOUNTID		SMALLINT UNSIGNED PRIMARY KEY,
EMAIL			VARCHAR(50),
USERNAME		VARCHAR(50),
FULLNAME		VARCHAR(50),
DEPARTMENTID	SMALLINT UNSIGNED,
POSITIONID		SMALLINT UNSIGNED,
CREATDATE		DATE,
FOREIGN KEY (DEPARTMENTID) REFERENCES DEPARTMENT (DEPARTMENTID) 
);

CREATE TABLE `GROUP` (
GROUPID		SMALLINT UNSIGNED PRIMARY KEY,
GROUPName	CHAR(30),
CreateDate	DATE
);

CREATE TABLE GROUPACCOUNT (
GROUPID		TINYINT UNSIGNED,
ACCOUNTID	SMALLINT UNSIGNED,
JOINDATE	DATE,
PRIMARY KEY	(GROUPID, ACCOUNTID)
);

CREATE TABLE TYPEQUESTION (
TYPEID		SMALLINT UNSIGNED PRIMARY KEY ,
TYPENAME	ENUM ('Essay', 'Multiple-Choice')
);

CREATE TABLE CATEGORYQUESTION (
CATEGORYID		SMALLINT UNSIGNED PRIMARY KEY,
CATEGORYNAME	CHAR(30)
);

CREATE TABLE QUESTION (
QUESTIONID		SMALLINT UNSIGNED PRIMARY KEY,
CONTENT			VARCHAR(100),
CATEGORYID		SMALLINT UNSIGNED,
TYPEID			SMALLINT UNSIGNED,
CREATORID		SMALLINT UNSIGNED,
CREATDATE		DATE
);

CREATE TABLE ANSWER (
ANSWERID		SMALLINT UNSIGNED PRIMARY KEY,
CONTENT			CHAR(30),
QUESTIONID		SMALLINT UNSIGNED,
ISCORRECT		BIT
);

CREATE TABLE EXAM (
EXAMID		SMALLINT UNSIGNED PRIMARY KEY,
`CODE`		CHAR(50),
TITLE		VARCHAR(50),
CATEGORYID	TINYINT UNSIGNED,
DURATION	DATETIME,
CREATORID	SMALLINT UNSIGNED,
CREATEDATE	DATE
);

CREATE TABLE EXAMQUESTION (
EXAMID		SMALLINT UNSIGNED,
QUESTIONID	SMALLINT UNSIGNED,
PRIMARY KEY	(EXAMID, QUESTIONID)
);
