export const LOGIN = "LOGIN";
export const LOGOUT = "LOGOUT";
export const GET_LIST_EMPLOYEE = "GET_LIST_EMPLOYEE";
export const CREATE_EMPLOYEE = "CREATE_EMPLOYEE";
export const UPDATE_EMPLOYEE = "UPDATE_EMPLOYEE";
export const DELETE_EMPLOYEE = "DELETE_EMPLOYEE";


